### PR TITLE
Tests with Grizzly now map exceptions properly

### LINKED ISSUE #1057: ExceptionMapper response body is not being returned in tests (protected routes only)
Given a custom exception mapper like this one: 

```
public class CustomExceptionMapper implements ExceptionMapper<Exception> {

    @Override
    public Response toResponse(final Exception exception) {
        return Response.status(599) //
                .entity(exception.getMessage()) //
                .type("text/plain") //
                .build();
    }
}
```

And a resource route that fails (throwing a business exception or something). Using as example, this one:

```
    @RolesAllowed({"ADMIN"})
    @GET
    @Path("fail")
    public String thisFails(@Context SecurityContext securityContext) {
        throw new RuntimeException("My exception message");
    }
````

It's expected to this test to pass:

```
Response response = target("/test/fail").request()
                       .header(HttpHeaders.AUTHORIZATION, "Basic Z29vZC1ndXk6c2VjcmV0")
                       .get();
                               
assertThat(response.getStatus()).isEqualTo(599); // This is ok.
assertThat(response.readEntity(String.class)).isEqualTo("My exception message"); // This fails.
````

But just only the status code is respected, the body is not.

```
org.junit.ComparisonFailure: expected:<"[My exception message]"> but was:<"[<html><head><title>Grizzly 2.3.16</title><style><!--div.header {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#003300;font-size:22px;-moz-border-radius-topleft: 10px;border-top-left-radius: 10px;-moz-border-radius-topright: 10px;border-top-right-radius: 10px;padding-left: 5px}div.body {font-family:Tahoma,Arial,sans-serif;color:black;background-color:#FFFFCC;font-size:16px;padding-top:10px;padding-bottom:10px;padding-left:10px}div.footer {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#666633;font-size:14px;-moz-border-radius-bottomleft: 10px;border-bottom-left-radius: 10px;-moz-border-radius-bottomright: 10px;border-bottom-right-radius: 10px;padding-left: 5px}BODY {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;}B {font-family:Tahoma,Arial,sans-serif;color:black;}A {color : black;}HR {color : #999966;}--></style> </head><body><div class="header">CUSTOM</div><div class="body">CUSTOM</div><div class="footer">Grizzly 2.3.16</div></body></html>]">
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at 
	...omitted
```

I'm trying to figure out how to fix this issue. I've been working on this in my fork, here is the commit with unit test that fails: https://github.com/thiagomoretto/dropwizard/commit/ef6537609cdfbf13312a349ee693ebaf27cdc3f3. Would be awesome if someone could help me to find out how to solve this issue, a tip or something like. I could work on this to send a PR, but still I didn't found the root cause of the problem.

### PR DESCRIPTION
**Pull request by nickbabcock**
When using Grizzly with `ResourceTestRule`, it didn't know how to map exceptions (it would just return the generic Grizzly error page, which is not useful for testing). This pull request fixes this by turning on `RESPONSE_SET_STATUS_OVER_SEND_ERROR`

Closes #1057 (though it only mentioned protected routes)

### CODE REVIEW

File: dropwizard-testing/src/test/java/io/dropwizard/testing/app/ResourceTestWithGrizzly.java [hunk 1]
```diff
@@ -19,13 +20,32 @@
     @ClassRule
     public static final ResourceTestRule resources = ResourceTestRule.builder()
             .addResource(new ContextInjectionResource())
-            .setTestContainerFactory(new GrizzlyTestContainerFactory())
+            .setTestContainerFactory(new GrizzlyWebTestContainerFactory())
+            .addProvider(new RuntimeExceptionMapper())
             .build();
 
+    private static class RuntimeExceptionMapper implements ExceptionMapper<RuntimeException> {
```
Comment (arteam) [inline dropwizard-testing/src/test/java/io/dropwizard/testing/app/ResourceTestWithGrizzly.java]: I'm nitpicking again, but it would be great if you moved this class to the start or to the end of `ResourceTestWithGrizzly`. It makes the outer class more focused.

Comment (nickbabcock) [inline dropwizard-testing/src/test/java/io/dropwizard/testing/app/ResourceTestWithGrizzly.java]: Happy to oblige :+1:

**Comment by arteam** [comment]
Thanks for your work on this.

**Comment by carlo-rtr** [comment]
Nice. It's all about finding the hidden features!
