### PR TITLE
Register default mappers in ResourceTestRule

### LINKED ISSUE #808: 500 error on malformed JSON
Consider the following test:

```java
import javax.ws.rs.*;
import javax.ws.rs.client.Entity;
import javax.ws.rs.core.Response;

import io.dropwizard.testing.junit.ResourceTestRule;
import org.junit.ClassRule;
import org.junit.Test;

import static javax.ws.rs.core.MediaType.APPLICATION_JSON;
import static javax.ws.rs.core.MediaType.APPLICATION_JSON_TYPE;
import static org.assertj.core.api.Assertions.assertThat;

public class PersonResourceTest {
    @ClassRule
    public static final ResourceTestRule resources = ResourceTestRule.builder()
            .addResource(new PersonResource())
            .build();

    @Test
    public void testShouldThrowBadRequestOnDodgyJson() {
        String json = "{\"name\":\"blah\u0006\", \"email\":\"blah\u0006@example.com\"}";
        Response response = resources.client().target("/person").request().post(Entity.entity(json, APPLICATION_JSON_TYPE));
        assertThat(response.getStatus()).isEqualTo(400);
    }

    @Path("/person")
    private static class PersonResource {
        @POST
        @Consumes(APPLICATION_JSON)
        public void save(Person person) {
        }
    }
}
```

The JSON posted to the resource contains an unescaped control character - according to [RFC 4627, section 2.5](https://tools.ietf.org/html/rfc4627#section-2.5), these should be escaped with a backslash.  However, in this case, Dropwizard returns a 500 error, logging this stack trace:

```
Illegal unquoted character ((CTRL-CHAR, code 6)): has to be escaped using backslash to be included in string value
 at [Source: org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream@464649c; line: 1, column: 15]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1419)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:508)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._throwUnquotedSpace(ParserMinimalBase.java:472)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._finishString2(UTF8StreamJsonParser.java:2235)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._finishString(UTF8StreamJsonParser.java:2165)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.getText(UTF8StreamJsonParser.java:279)
	at com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:29)
	at com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:12)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:538)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:344)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1056)
	at com.fasterxml.jackson.module.afterburner.deser.SuperSonicBeanDeserializer.deserializeFromObject(SuperSonicBeanDeserializer.java:199)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:124)
	at com.fasterxml.jackson.module.afterburner.deser.SuperSonicBeanDeserializer.deserialize(SuperSonicBeanDeserializer.java:118)
	at com.fasterxml.jackson.databind.ObjectReader._bind(ObjectReader.java:1232)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:676)
	at com.fasterxml.jackson.jaxrs.base.ProviderBase.readFrom(ProviderBase.java:808)
	at io.dropwizard.jersey.jackson.JacksonMessageBodyProvider.readFrom(JacksonMessageBodyProvider.java:60)
	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.invokeReadFrom(ReaderInterceptorExecutor.java:258)
	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.aroundReadFrom(ReaderInterceptorExecutor.java:234)
	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor.proceed(ReaderInterceptorExecutor.java:154)
	at org.glassfish.jersey.spi.ContentEncoder.aroundReadFrom(ContentEncoder.java:126)
	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor.proceed(ReaderInterceptorExecutor.java:154)
	at org.glassfish.jersey.server.internal.MappableExceptionWrapperInterceptor.aroundReadFrom(MappableExceptionWrapperInterceptor.java:73)
	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor.proceed(ReaderInterceptorExecutor.java:154)
	at org.glassfish.jersey.message.internal.MessageBodyFactory.readFrom(MessageBodyFactory.java:1124)
	at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:851)
	at org.glassfish.jersey.server.ContainerRequest.readEntity(ContainerRequest.java:270)
	at org.glassfish.jersey.server.internal.inject.EntityParamValueFactoryProvider$EntityValueFactory.provide(EntityParamValueFactoryProvider.java:96)
	at org.glassfish.jersey.server.spi.internal.ParameterValueHelper.getParameterValues(ParameterValueHelper.java:81)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$AbstractMethodParamInvoker.getParamValues(JavaResourceMethodDispatcherProvider.java:121)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$VoidOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:136)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:104)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:384)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:342)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:101)
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:271)
    ...
```

We should return a 400 response instead, common with other JSON processing failures.  Observed on DW 0.7.0 and 0.8.0-rc1.

### PR DESCRIPTION
**Pull request by nickbabcock**
The default exception mappers are not registered in `ResourceTestRule`, which may be an annoyance to users, as they would have know what the defaults are and know to re-register them if their tests relied on functionality the exception mappers provided. This pull requests fixes this situation by registering them out of the box.

The only users who would be negatively affected by this pull request are those that turn off `registerDefaultExceptionMappers` in the configuration and choose not to define new mappers to replace them. Those that override default exception mappers in the application will still override them in `ResourceTestRule` as usual.

Closes #808

### CODE REVIEW

File: dropwizard-testing/src/test/java/io/dropwizard/testing/app/PersonResource.java [hunk 1]
```diff
@@ -4,10 +4,8 @@
 import com.google.common.collect.ImmutableList;
 import io.dropwizard.testing.Person;
 
-import javax.ws.rs.GET;
-import javax.ws.rs.Path;
-import javax.ws.rs.PathParam;
-import javax.ws.rs.Produces;
+import javax.validation.Valid;
+import javax.ws.rs.*;
```
Comment (joschi) [inline dropwizard-testing/src/test/java/io/dropwizard/testing/app/PersonResource.java]: Please don't use wildcard imports.

**Comment by jplock** [comment]
I think this is good.  `ResourceTestRule` should work out of the box with the default configuration.  I think if a user uses `registerDefaultExceptionMappers`, then they should also be expected to update `ResourceTestRule` in their tests accordingly.

File: dropwizard-testing/src/test/java/io/dropwizard/testing/app/PersonResource.java (hunk 1 above)
Comment (nickbabcock) [inline dropwizard-testing/src/test/java/io/dropwizard/testing/app/PersonResource.java]: Fixed. Sometimes the IDE gets a little aggressive with imports :blush:

**Comment by joschi** [comment]
LGTM. :+1:

**Comment by scho** [comment]
Does this take the configuration (`AbstractServerFactory::getRegisterDefaultExceptionMappers`) into account?

**Comment by nickbabcock** [comment]
No, it doesn't. Do you have a use case where it matters?

**Comment by scho** [comment]
In our application, we disable adding the default exception mappters in order to customize some of them. It would be nice to not loose that ability. Maybe make it configurable?

**Comment by nickbabcock** [comment]
If you override/customize them in your application, then shouldn't need to set `registerDefaultExceptionMappers` to false.

Saying that, I realized that this pull request registers the default exception mappers in the wrong place for `ResourceTestRule`, so that you can't override them with your own. So I'll be back with the fix and test cases to ensure the functionality.
