### PR TITLE
Commit a database transaction in the `RESP_FILTERS_START` stage

### LINKED ISSUE #1604: Hibernate insert/update exceptions not being returned to the client
**Version: 1.0.0RC3**

The fix to allow lazy loading of POJOs during serialization has introduced a key issue. We are no longer seeing SQLExceptions during an insert/update//delete being reported back to the client.

In 1.0.0RC3, the session will be closed and the transaction committed only after the serialization has happened. If there are any database exceptions during the transaction commit (column val exceed/constraints etc..), they now happen only after the serialized response has been sent back. So the client assumes things are fine, but actually the server logs show the exception.

I guess we will still need to end the transaction or commit it in the RESP_FILTERS_START event. And session can be closed in FINISHED event. 

Here's the pull that introduced this issue, https://github.com/dropwizard/dropwizard/pull/1466

### PR DESCRIPTION
**Pull request by arteam**
But close the session during the `FINISHED` stage. This allows to the user to catch errors during commiting transactions (constraint violations, e.g) and map them to HTTP error with
an exception mapper.

This approach also is compatible with lazy loading, because the session remain open during serializing Hibernate entities.

Fix #1604

### CODE REVIEW

File: dropwizard-example/src/main/java/com/example/helloworld/HelloWorldApplication.java [hunk 1]
```diff
@@ -89,6 +89,7 @@ public void run(HelloWorldConfiguration configuration, Environment environment)
                 .setAuthorizer(new ExampleAuthorizer())
                 .setRealm("SUPER SECRET STUFF")
                 .buildAuthFilter()));
+        environment.jersey().
```
Comment (joschi) [inline dropwizard-example/src/main/java/com/example/helloworld/HelloWorldApplication.java]: That line probably doesn't belong here. :wink:

File: dropwizard-hibernate/src/main/java/io/dropwizard/hibernate/UnitOfWorkAspect.java [hunk 2]
```diff
@@ -80,7 +77,16 @@ public void onError() {
         try {
             rollbackTransaction();
         } finally {
-            session.close();
+            onFinish();
+        }
+    }
+
+    public void onFinish() {
```
Comment (joschi) [inline dropwizard-hibernate/src/main/java/io/dropwizard/hibernate/UnitOfWorkAspect.java]: Couldn't this lead to a session/memory leak?

File: dropwizard-example/src/main/java/com/example/helloworld/HelloWorldApplication.java (hunk 1 above)
Comment (arteam) [inline dropwizard-example/src/main/java/com/example/helloworld/HelloWorldApplication.java]: Yeah, a copy-paste error. A kindle reminder to myself to never use `git add .`

File: dropwizard-hibernate/src/main/java/io/dropwizard/hibernate/UnitOfWorkAspect.java (hunk 2 above)
Comment (arteam) [inline dropwizard-hibernate/src/main/java/io/dropwizard/hibernate/UnitOfWorkAspect.java]: There is a possibility, but I think we can presume that Jersey will always generate a `FINISHED` event, and `onFinish` will be called and it will clean up resources.

Comment (pkwarren) [inline dropwizard-hibernate/src/main/java/io/dropwizard/hibernate/UnitOfWorkAspect.java]: According to the docs, it sounds like this is called on success or failure: 

https://github.com/jersey/jersey/blob/5f9e5fb78d48ce45431032a5867c157f191716fc/core-server/src/main/java/org/glassfish/jersey/server/monitoring/RequestEvent.java#L174-L179

**Comment by pkwarren** [comment]
👍

File: dropwizard-hibernate/src/main/java/io/dropwizard/hibernate/UnitOfWorkAspect.java (hunk 2 above)
Comment (joschi) [inline dropwizard-hibernate/src/main/java/io/dropwizard/hibernate/UnitOfWorkAspect.java]: ✅
