### PR TITLE
Rethrow Hibernate exceptions as Jersey exceptions

### LINKED ISSUE #949: Custom ExceptionMapper not invoked when Hibernate rollback
Using DW 0.8.0, Java 8

I have one custom exception mapper to handle `hibernate` exception:
```java
import org.hibernate.exception.ConstraintViolationException;


@Provider
public class SQLConstraintViolationExceptionMapper implements ExceptionMapper<ConstraintViolationException> {
    ....
}
```

I registered the mapper https://github.com/paukiatwee/budgetapp/blob/master/src/main/java/io/budgetapp/BudgetApplication.java#L143

When `org.hibernate.exception.ConstraintViolationException` exception is thrown when foreign key violation occurred, `SQLConstraintViolationExceptionMapper` is no called.

You can reproduce the problem by running this integration test https://github.com/paukiatwee/budgetapp/blob/master/src/test/java/io/budgetapp/resource/CategoryResourceIT.java#L65

This might caused by https://github.com/dropwizard/dropwizard/blob/master/dropwizard-hibernate/src/main/java/io/dropwizard/hibernate/UnitOfWorkApplicationListener.java#L87 exception not handled by container.

Working fine for DW 0.7.0

### PR DESCRIPTION
**Pull request by arteam**
If a database commit fails, it's better not to rethrow an Hibernate exception in the original form, but
wrap it as a MappableException.

This way users can map sql exceptions to web responses and derive a business value from the
database validation checks.

Resolve #949

### CODE REVIEW

File: dropwizard-hibernate/src/test/java/io/dropwizard/hibernate/DataExceptionMapper.java [hunk 1]
```diff
@@ -0,0 +1,26 @@
...
+
+    private static final Logger LOGGER = LoggerFactory.getLogger(DataException.class);
+
+    @Override
+    public Response toResponse(DataException e) {
+        LOGGER.error("Hibernate error", e);
+        String message = e.getCause().getMessage().contains("EMAIL") ? "Wrong email" : "Wrong input";
+
+        return Response.status(Response.Status.BAD_REQUEST)
+                .entity(ImmutableMap.of("error", message))
```
Comment (joschi) [inline dropwizard-hibernate/src/test/java/io/dropwizard/hibernate/DataExceptionMapper.java]: For the sake of consistency the response should be built using [`ErrorMessage`](https://github.com/dropwizard/dropwizard/blob/v0.8.0/dropwizard-jersey/src/main/java/io/dropwizard/jersey/errors/ErrorMessage.java).

Comment (arteam) [inline dropwizard-hibernate/src/test/java/io/dropwizard/hibernate/DataExceptionMapper.java]: That makes sense. Reused `ErrorMessage` for error message generation and testing.

File: dropwizard-hibernate/src/main/java/io/dropwizard/hibernate/UnitOfWorkApplicationListener.java [hunk 2]
```diff
@@ -84,7 +85,7 @@ else if (event.getType() == RequestEvent.Type.RESP_FILTERS_START) {
                         commitTransaction();
                     } catch (Exception e) {
                         rollbackTransaction();
-                        this.<RuntimeException>rethrow(e);
+                        throw new MappableException(e);
```
Comment (joschi) [inline dropwizard-hibernate/src/main/java/io/dropwizard/hibernate/UnitOfWorkApplicationListener.java]: I'm a little bit uncomfortable with using an exception class clearly being used only (?) internally by Jersey. Maybe we could use a second `catch` block before this one which catches [`HibernateException`](https://docs.jboss.org/hibernate/orm/4.3/javadocs/org/hibernate/HibernateException.html) (which inherits from RuntimeException) and re-throw it unchanged while we use [`Throwables#propagateIfPossible(java.lang.Throwable)`](http://docs.guava-libraries.googlecode.com/git/javadoc/com/google/common/base/Throwables.html#propagateIfPossible(java.lang.Throwable)) in the catch-all block (which is currently throwing the MappableException).

File: dropwizard-jersey/src/main/java/io/dropwizard/jersey/errors/ErrorMessage.java [hunk 3]
```diff
@@ -1,5 +1,8 @@
 package io.dropwizard.jersey.errors;
 
+import com.fasterxml.jackson.annotation.JsonCreator;
+import com.fasterxml.jackson.annotation.JsonProperty;
+
```
Comment (jplock) [inline dropwizard-jersey/src/main/java/io/dropwizard/jersey/errors/ErrorMessage.java]: Can we also add `@JsonInclude(JsonInclude.Include.NON_NULL)` in here to avoid having null fields show up in the error responses if they aren't being set? (I ran into this with the `details` field)

Comment (joschi) [inline dropwizard-jersey/src/main/java/io/dropwizard/jersey/errors/ErrorMessage.java]: :+1:

File: dropwizard-hibernate/src/main/java/io/dropwizard/hibernate/UnitOfWorkApplicationListener.java (hunk 2 above)
Comment (arteam) [inline dropwizard-hibernate/src/main/java/io/dropwizard/hibernate/UnitOfWorkApplicationListener.java]: * I beleive Jersey already takes care of propogating an original exception, if a mapping has not been found. [Source](https://github.com/jersey/jersey/blob/master/core-server/src/main/java/org/glassfish/jersey/server/ServerRuntime.java#L612-619).
* Do we really have checked exceptions? `commitTransaction` doesn't throw any.

Comment (joschi) [inline dropwizard-hibernate/src/main/java/io/dropwizard/hibernate/UnitOfWorkApplicationListener.java]: Good point. So we could simply catch `RuntimeException` instead of `Exception` and re-throw after we rolled back the transaction. No need to wrap it in either `MappableException` or `RuntimeException`. This should make life easier for us. :smile:

Comment (arteam) [inline dropwizard-hibernate/src/main/java/io/dropwizard/hibernate/UnitOfWorkApplicationListener.java]: But that returns us to the original version. The whole idea is to wrap an exception to `MappableException`, so Jersey will try to find exception mappers.

Comment (joschi) [inline dropwizard-hibernate/src/main/java/io/dropwizard/hibernate/UnitOfWorkApplicationListener.java]: The original version casted every Exception to `RuntimeException`. Might this have caused the problem with Jersey not trying to map the specific exception with a registered exception mapper?

Comment (arteam) [inline dropwizard-hibernate/src/main/java/io/dropwizard/hibernate/UnitOfWorkApplicationListener.java]: Well, if we don't wrap an exception
````java
try {
    commitTransaction();
} catch (RuntimeException e) {
    rollbackTransaction();
    throw e;
}
````
Then `testSqlExceptionIsHandled` fails with 500 error.

If we delibitraly throw `DataException` from a resource then the mapper works, because Jersey internally wraps the exception as `MappingException`. But, as I beleive, it does so only for resources, but not for application listeners.

**Comment by joschi** [comment]
LGTM.
